### PR TITLE
Include suggestions in GitHub output

### PR DESCRIPTION
**Pull request by DanRigby**
This PR adds support for displaying suggestion level issues as notice annotations in the GitHub Actions output.

### CODE REVIEW

**Comment by DanRigby** [comment]
cc @smoogipoo you appear to be the author of the GitHub output module.

**Review by smoogipoo — APPROVED** [review]
lgtm!

**Comment by laedit** [comment]
Thanks a lot!  
Will try to release asap.

**Comment by DanRigby** [comment]
Looks like it’s working :)

91916911-522B-4A8D-AEE1-E5C3A5FB7203

**Pull request merged**
